Repository Kav-K/GPT3Discord, pull requests merged in 2023-01, with the labels that each got.

#35 Add gitignore and change role checks
  .gitignore
  cogs/draw_image_generation.py
  cogs/gpt_3_commands_and_converser.py
  cogs/image_prompt_optimizer.py
  gpt3discord.py
  models/check_model.py
Labels: enhancement

#48 Slashgroups refactor and separation of commands based on roles
  .gitignore
  cogs/draw_image_generation.py
  cogs/gpt_3_commands_and_converser.py
  cogs/image_prompt_optimizer.py
  gpt3discord.py
  models/check_model.py
  models/env_service_model.py
  pyproject.toml
  requirements.txt
  sample.env
Labels: enhancement

#61 Gpt end
  README.md
  cogs/gpt_3_commands_and_converser.py
Labels: enhancement

#55 Added passthrough of gpt3 parameters to /ask
  README.md
  cogs/gpt_3_commands_and_converser.py
  models/openai_model.py
Labels: enhancement

#60 Changed the image resizing to go by the guild filesize limit
  cogs/draw_image_generation.py
  cogs/image_prompt_optimizer.py
  models/openai_model.py
Labels: enhancement

#58 Autocomplete and changed the way opener files are loaded to use a folder instead
  README.md
  cogs/gpt_3_commands_and_converser.py
  models/autocomplete_model.py
  openers/english_translator.txt
  openers/javascript_console.txt
Labels: enhancement

#75 Long term memory with pineconedb
  README.md
  cogs/gpt_3_commands_and_converser.py
  conversation_starter_pretext.txt
  gpt3discord.py
  models/autocomplete_model.py
  models/message_model.py
  models/openai_model.py
  models/pinecone_service_model.py
  models/user_model.py
Labels: enhancement, high-prio

#53 Changes to environment loading.
  Dockerfile
  README.md
  cogs/gpt_3_commands_and_converser.py
  cogs/image_prompt_optimizer.py
  gpt3discord.py
  models/autocomplete_model.py
  models/env_service_model.py
Labels: high-prio, help-wanted-important

#80 Multi tenancy api key support
  Dockerfile
  README.md
  cogs/draw_image_generation.py
  cogs/gpt_3_commands_and_converser.py
  cogs/image_prompt_optimizer.py
  gpt3discord.py
  models/env_service_model.py
  models/openai_model.py
  models/pinecone_service_model.py
  pyproject.toml
  requirements.txt
  sample.env
Labels: enhancement, high-prio, help-wanted-important

#102 context menu buttons
  README.md
  cogs/commands.py
  cogs/image_service_cog.py
  cogs/text_service_cog.py
  gpt3discord.py
  services/image_service.py
  services/text_service.py
Labels: enhancement

#104 Added some docstrings, some bugfixes and general cleaning
  cogs/commands.py
  cogs/image_service_cog.py
  cogs/moderations_service_cog.py
  cogs/prompt_optimizer_cog.py
  cogs/text_service_cog.py
  gpt3discord.py
  models/autocomplete_model.py
  models/check_model.py
  models/openai_model.py
  models/user_model.py
  services/deletion_service.py
  services/environment_service.py
  services/image_service.py
  services/message_queue_service.py
  services/moderations_service.py
  services/pinecone_service.py
  services/text_service.py
  services/usage_service.py
Labels: documentation, enhancement

#122 persistent settings
  cogs/commands.py
  cogs/text_service_cog.py
  gpt3discord.py
  models/openai_model.py
  services/text_service.py
Labels: enhancement
